sonar.projectKey=dbt-lakehouse-poc
sonar.projectName=dbt-lakehouse-poc
sonar.sources=.
sonar.exclusions=.venv/**,data/**,output/**,**/__pycache__/**,*.ipynb
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
